
default_platform(:ios)

#指定项目的scheme即:App名称
scheme = “XLsn0wApp”

#蒲公英api_key和user_key
pgyer_api_key  = "8cf272d1f1644ef6cdc5899ba"
pgyer_user_key = "73d7a4869e961756975d33e8"

# App专用密码: Apple ID开启两步验证后 专门设置一个用于fastlane上传的密码
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD = "osfh-zvij-selv"

platform :ios do

puts "lane执行ad-hoc脚本"

lane :adhoc do|options|
branch = options[:branch]

# “gym开始执行ad-hoc打包ipa”

# 指定Xcode版本
xcode_select("/Applications/Xcode.app")

gym(
# 输出的ipa名称
output_name:”#{scheme}”,
# 是否清空以前的编译信息 true：是
clean:true,
# 指定打包方式，Release 或者 Debug
configuration:"Release",
# 指定打包所使用的输出方式，目前支持app-store, package, ad-hoc, enterprise, development
export_method:"ad-hoc",
# 指定输出文件夹
output_directory:"./fastlane/ad-hoc",
)

puts "开始上传蒲公英"

# 蒲公英上传需要设置密码 pgyer(api_key: “#{pgyer_api_key}”, user_key: “#{pgyer_user_key}”)
pgyer(api_key: “#{pgyer_api_key}”, user_key: “#{pgyer_user_key}”, password: "bjt", install_type: "2")

end

end
